/*
NomeObjeto: MGSTCTCONTRATO
TipoObjeto: TABLE
NomeTabela: MGSTCTCONTRATO
Executar  : SE_NAO_EXISTIR
*/ 

CREATE TABLE "MGSTCTCONTRATO"
   (
	"NUMCONTRATO" NUMBER(10,0),
	"CODTIPSITUACAO" NUMBER(10,0), 
	"DTINICIO" DATE,
	"DTFIM" DATE,
	"CODPARC" NUMBER(10,0), 
	"DTASSINATURA" DATE,
	"VLRMES" FLOAT(126),
	"VLRTOTAL" FLOAT(126),
	"OBSCONTRATO" VARCHAR2(100 BYTE)
   ) 
/

/*
NomeObjeto: MGSTCTMODALCONTR
TipoObjeto: TABLE
NomeTabela: MGSTCTMODALCONTR
Executar  : SE_NAO_EXISTIR
*/ 

CREATE TABLE "MGSTCTMODALCONTR"
   (
	"NUMODALIDADE" NUMBER(10,0), 
    "NUMCONTRATO" NUMBER(10,0), 
    "CODTPN" NUMBER(10,0), 
	"NUTIPOSERVICO" NUMBER(10,0) 
   ) 
/

/*
NomeObjeto: MGSTCTCONTRATOPREV
TipoObjeto: TABLE
NomeTabela: MGSTCTCONTRATOPREV
Executar  : SE_NAO_EXISTIR
*/ 

CREATE TABLE "MGSTCTCONTRATOPREV"
   (
	"NUCONTRPREV" NUMBER(10,0), 
	"NUMODALIDADE" NUMBER(10,0), 
    "NUMCONTRATO" NUMBER(10,0), 
    "CODTIPOPOSTO" NUMBER(10,0), 
	"CODSERVMATERIAL" NUMBER(10,0),
	"CODEVENTO" NUMBER(10,0), 
	"QTDCONTRATADA" NUMBER(10,0),
	"VLRUNITARIO" FLOAT(126),
	"VLRCONTRATADA" FLOAT(126),
	"CODCONTROLE" NUMBER(10,0)
   ) 
/

/

/*
NomeObjeto: MGSTCTLOCALCONT
TipoObjeto: TABLE
NomeTabela: MGSTCTLOCALCONT
Executar  : SE_NAO_EXISTIR
*/ 

CREATE TABLE "MGSTCTLOCALCONT"
   (
	"NULOCALCONT" NUMBER(10,0), 
	"NUMODALIDADE" NUMBER(10,0), 
    "NUMCONTRATO" NUMBER(10,0), 
	"NUMLOCAL" NUMBER(10,0),
	"CODPARC" NUMBER(10,0), 
	"CEP" VARCHAR2(8 BYTE), 
	"CODCID" NUMBER(10,0), 
	"CODBAI" NUMBER(10,0), 
	"CODEND" NUMBER(10,0), 
	"COMPLEMENTO" VARCHAR2(100 BYTE),
	"NUMERO" NUMBER(10,0),
	"CODUF" NUMBER(5,0),
      "CODCIDNF" NUMBER(10,0)
   ) 
/

/*
NomeObjeto: MGSTCTCONTRCENT
TipoObjeto: TABLE
NomeTabela: MGSTCTCONTRCENT
Executar  : SE_NAO_EXISTIR
*/ 

CREATE TABLE "MGSTCTCONTRCENT"
   (
	"NUCONTRCENT" NUMBER(10,0), 
	"NULOCALCONT" NUMBER(10,0), 
	"NUMCONTRATO" NUMBER(10,0), 
	"CODSITEPAI" NUMBER(10,0), 
	"CODSITE" NUMBER(10,0), 
	"DTINICIO" DATE,
	"DTFIM" DATE
   ) 
/

/*
NomeObjeto: MGSTCTLOCALTIPOFAT
TipoObjeto: TABLE
NomeTabela: MGSTCTLOCALTIPOFAT
Executar  : SE_NAO_EXISTIR
*/ 

CREATE TABLE "MGSTCTLOCALTIPOFAT"
   (
	"NULOCALTIPOFAT" NUMBER(10,0), 
	"CODTIPOFATURA" NUMBER(10,0), 
	"NULOCALCONT" NUMBER(10,0), 
	"NUMCONTRATO" NUMBER(10,0) 
   ) 
/

/*
NomeObjeto: MGSTCTTIPOFATURA
TipoObjeto: TABLE
NomeTabela: MGSTCTTIPOFATURA
Executar  : SE_NAO_EXISTIR
*/ 

CREATE TABLE "MGSTCTTIPOFATURA"
   (
	"CODTIPOFATURA" NUMBER(10,0), 
	"DESCRTIPOFAT" VARCHAR2(100 BYTE)
   ) 
/

/*
NomeObjeto: MGSTCTCONTRATOTRIB
TipoObjeto: TABLE
NomeTabela: MGSTCTCONTRATOTRIB
Executar  : SE_NAO_EXISTIR
*/ 

CREATE TABLE "MGSTCTCONTRATOTRIB"
   (
	"NUCONTRATOTRIB" NUMBER(10,0), 
	"NULOCALTIPOFAT" NUMBER(10,0), 
	"CODPROD" NUMBER(10,0), 
	"DTINICIO" DATE,
	"DTFIM" DATE,
	"ATIVO" VARCHAR2(1 BYTE)
   ) 
/

/*
NomeObjeto: MGSTCTCONTRATOTAXA
TipoObjeto: TABLE
NomeTabela: MGSTCTCONTRATOTAXA
Executar  : SE_NAO_EXISTIR
*/ 

CREATE TABLE "MGSTCTCONTRATOTAXA"
   (
	"NUCONTRTAXA" NUMBER(10,0), 
	"NULOCALTIPOFAT" NUMBER(10,0), 
	"CODTAXA" NUMBER(10,0),
	"DTINICIO" DATE,
	"DTFIM" DATE,
	"VLRTAXA" FLOAT(126),
	"ATIVO" VARCHAR2(1 BYTE),
	"FORMULA" VARCHAR2(100 BYTE)
   ) 
/

/*
NomeObjeto: MGSTCTTIPOTAXA
TipoObjeto: TABLE
NomeTabela: MGSTCTTIPOTAXA
Executar  : SE_NAO_EXISTIR
*/ 

CREATE TABLE "MGSTCTTIPOTAXA"
	(
	 "CODTAXA" NUMBER(10,0), /*PK*/
	 "DESCRTAXA" VARCHAR2(100 BYTE),
	 "VLRPADRAO"	FLOAT(126)
	)
/

/*
NomeObjeto: MGSTCTUNIDADEPREV
TipoObjeto: TABLE
NomeTabela: MGSTCTUNIDADEPREV
Executar  : SE_NAO_EXISTIR
*/ 

CREATE TABLE "MGSTCTUNIDADEPREV"
   (
	"NUUNIDPREV" NUMBER(10,0), 
	"NUCONTRCENT" NUMBER(10,0), 
	"CODTIPOPOSTO" NUMBER(10,0), 
	"CODSERVMATERIAL" NUMBER(10,0),
	"CODEVENTO" NUMBER(10,0), 
	"QTDCONTRATADA" NUMBER(10,0),
	"VLRUNITARIO" FLOAT(126),
	"VLRCONTRATADA" FLOAT(126),
	"DTINICIO" DATE,
	"DTFIM" DATE,
	"QTDEMPREGADOS" NUMBER(10,0),
	"CODCONTROLE" NUMBER(10,0)
   ) 
/

/

/*
NomeObjeto: MGSTCTCONTROLE
TipoObjeto: TABLE
NomeTabela: MGSTCTCONTROLE
Executar  : SE_NAO_EXISTIR
*/ 

CREATE TABLE "MGSTCTCONTROLE"
   (
	"CODCONTROLE" NUMBER(10,0), 
	"DESCRCONTROLE" VARCHAR2(100 BYTE)
   ) 
/

/*
NomeObjeto: MGSTCTTIPOSITUACAO
TipoObjeto: TABLE
NomeTabela: MGSTCTTIPOSITUACAO
Executar  : SE_NAO_EXISTIR
*/ 

CREATE TABLE "MGSTCTTIPOSITUACAO"
   (
	"CODTIPSITUACAO" NUMBER(10,0), 
	"DESCRSITUACAO" VARCHAR2(100 BYTE)
   ) 
/

/*
NomeObjeto: MGSTCTMETRICAS
TipoObjeto: TABLE
NomeTabela: MGSTCTMETRICAS
Executar  : SE_NAO_EXISTIR
*/ 

CREATE TABLE "MGSTCTMETRICAS"
   (
	"NUMETRICAS" NUMBER(10,0), 
	"NUMCONTRATO" NUMBER(10,0), 
	"GCPOSTO" VARCHAR2(100 BYTE),
	"GCPOSTORETRO" VARCHAR2(100 BYTE),
	"GCFERIAS" VARCHAR2(100 BYTE),
	"GCLICENCAS" VARCHAR2(100 BYTE),
	"GCHORAS" VARCHAR2(100 BYTE),
	"GCSUSBT" VARCHAR2(100 BYTE)
   ) 
/

/*
NomeObjeto: MGSTCTUNIDPREVVAGA
TipoObjeto: TABLE
NomeTabela: MGSTCTUNIDPREVVAGA
Executar  : SE_NAO_EXISTIR
*/ 

CREATE TABLE "MGSTCTUNIDPREVVAGA"
   (
	"NUUNIDPREVVAGA" NUMBER(10,0), /*PK*/
	"NUCONTRCENT" NUMBER(10,0), /*FK(MGSTCTCONTRCENT.NUCONTRCENT)*/
	"NUUNIDPREV" NUMBER(10,0), /*FK(MGSTCTUNIDADEPREV.NUUNIDPREV)*/
	"DTINICIO" DATE,
	"DTFIM" DATE,
	"CODVAGA" VARCHAR2(10) /*FK(MGSTCTVAGAS.CODVAGA)*/
   ) 
/

/

/*
NomeObjeto: MGSTCTVAGAS
TipoObjeto: TABLE
NomeTabela: MGSTCTVAGAS
Executar  : SE_NAO_EXISTIR
*/ 

CREATE TABLE "MGSTCTVAGAS"
   (
	"CODVAGA" VARCHAR2(10), /*PK*/
	"SIGLA" VARCHAR2(5),
	"NUMSEQ" NUMBER(10,0),
	"DTCRIAO" DATE,
	"DISPONIVEL" VARCHAR2(100 BYTE),
	"DTEXTINCAO" DATE
   ) 
/

/*
NomeObjeto: MGSTCTCONTRATOVAGA
TipoObjeto: TABLE
NomeTabela: MGSTCTCONTRATOVAGA
Executar  : SE_NAO_EXISTIR
*/ 

CREATE TABLE "MGSTCTCONTRATOVAGA"
   (
	"NUCONTRVAGA" NUMBER(10,0), /*PK*/
	"NUCONTRPREV" NUMBER(10,0), /*FK(MGSTCTCONTRATOPREV.NUCONTPREV)*/
	"CODVAGA" VARCHAR2(10), /*FK(MGSTCTVAGAS.CODVAGA)*/
	"DTINICIO" DATE,
	"DTFIM" DATE
	) 
/

/*
NomeObjeto: MGSTCTCONTRVLRPS
TipoObjeto: TABLE
NomeTabela: MGSTCTCONTRVLRPS
Executar  : SE_NAO_EXISTIR
*/ 

CREATE TABLE "MGSTCTCONTRVLRPS"
   (
    "NUCONTREVENTO" NUMBER(10,0), /*PK*/
    "NUMCONTRATO" NUMBER(10,0), /*FK(MGSTCTCONTRATO.NUMCONTRATO)*/
	"NUMODALIDADE" NUMBER(10,0), /*FK(MGSTCTMODALCONTR.NUMODALIDADE)*/
	"CODTIPOPOSTO" NUMBER(10,0), /*FK(AD_TGFPSS.CODPOSTO)*/
	"CODEVENTO" NUMBER(10,0), /*FK(AD_TGFECUS.CODEVENTO)*/
	"NROOCORENCIA" NUMBER(10,0),
	"DTINICIO" DATE,
	"DTFIM" DATE,
	"ALIQISS" FLOAT(126),
	"VLRTOTAL" FLOAT(126),
	"DTREFERCCT" DATE,
	"ALIQADM" FLOAT(126)
   ) 
/

/*
NomeObjeto: MGSTCTCONTRVLRSERV
TipoObjeto: TABLE
NomeTabela: MGSTCTCONTRVLRSERV
Executar  : SE_NAO_EXISTIR
*/ 

CREATE TABLE "MGSTCTCONTRVLRSERV"
   (
    "NUCONTRMATSRV" NUMBER(10,0), /*PK*/
	"NUMODALIDADE" NUMBER(10,0), /*FK(MGSTCTMODALCONTR.NUMODALIDADE)*/
	"NUMCONTRATO" NUMBER(10,0), /*FK(MGSTCTCONTRATO.NUMCONTRATO)*/
	"CODSERVMATERIAL" NUMBER(10,0), /*FK(TGFPRO.CODPROD)*/
	"CODEVENTO" NUMBER(10,0), /*FK(AD_TGFECUS.CODEVENTO)*/
	"NROOCORENCIA" NUMBER(10,0), 
	"DTINICIO" DATE, 
	"DTFIM" DATE, 
	"ALIQISS" FLOAT(126), 
	"VLRTOTAL" FLOAT(126), 
	"DTREFERCCT" DATE, 
	"ALIQADM" FLOAT(126)
   ) 
/

/*
NomeObjeto: MGSTCTPOSTOCARGO
TipoObjeto: TABLE
NomeTabela: MGSTCTPOSTOCARGO
Executar  : SE_NAO_EXISTIR
*/ 

CREATE TABLE "MGSTCTPOSTOCARGO"
	(
	 "NUPOSTOCARGO" NUMBER(10,0),
	 "CODCARGO" NUMBER(10,0),
	 "CODTIPOPOSTO" NUMBER(10,0)
	)
/

/*
NomeObjeto: MGSTCTALOCACAOSERV
TipoObjeto: TABLE
NomeTabela: MGSTCTALOCACAOSERV
Executar  : SE_NAO_EXISTIR
*/ 

CREATE TABLE "MGSTCTALOCACAOSERV"
   (
    "NUALOCASERV" NUMBER(10,0), /*PK*/
	"NUUNIDPREV" NUMBER(10,0), /*FK(MGSTCTUNIDADEPREV.NUUNIDPREV)*/
	"DTINICIO" DATE, 
	"DTFIM" DATE, 
	"STATUSALOCACAO" VARCHAR2(10 BYTE), 
	"DTINS" DATE, 
	"QTDEALOCACAO" NUMBER(10,0), 
	"VLRUNITARIO" FLOAT(126), 
	"VLRTOTAL" FLOAT(126)
   ) 
/

/*
NomeObjeto: MGSTCTALOCACAOPS
TipoObjeto: TABLE
NomeTabela: MGSTCTALOCACAOPS
Executar  : SE_NAO_EXISTIR
*/ 

CREATE TABLE "MGSTCTALOCACAOPS"
   (
    "NUALOCAPS" NUMBER(10,0),  /*PK*/
	"NUUNIDPREV" NUMBER(10,0), /*FK(MGSTCTUNIDADEPREV.NUUNIDPREV)*/
	"NUUNIDPREVVAGA" NUMBER(10,0), /*FK(MGSTCTUNIDPREVVAGA.NUUNIDPREVVAGA)*/
	"CODCARGO" NUMBER(10,0), 
	"MATRICULA" NUMBER(10,0), 
	"DTINICIO" DATE, 
	"DTFIM" DATE, 
	"STATUSALOCACAO" VARCHAR2(10 BYTE), 
	"DTINS" DATE, 
	"CODTIPOPOSTO" NUMBER(10,0), /*FK(AD_TGFPSS.CODPOSTO)*/
	"CODEVENTO" NUMBER(10,0) /*FK(AD_TGFECUS.CODEVENTO)*/
   ) 
/

/*
NomeObjeto: MGSTCTEVTAPT
TipoObjeto: TABLE
NomeTabela: MGSTCTEVTAPT
Executar  : SE_NAO_EXISTIR
*/ 

CREATE TABLE "MGSTCTEVTAPT"
   (
    "NUEVTAPT" NUMBER(10,0), /*PK*/
	"NUMCONTRATO" NUMBER(10,0), /*FK(MGSTCTCONTRATO.NUMCONTRATO)*/
	"CODEVENTO" NUMBER(10,0), /*FK(AD_TGFECUS.CODEVENTO)*/
	"CODAPONTAMENTO" VARCHAR2(100 BYTE), 
	"TIPAPONTAMENTO" VARCHAR2(100 BYTE), 
	"FR_APONTAMENTO" VARCHAR2(100 BYTE), 
	"CODORIGEM" VARCHAR2(100 BYTE), 
	"TABORIGEM" VARCHAR2(100 BYTE), 
	"TIPPERIODO" VARCHAR2(100 BYTE), 
	"VA" VARCHAR2(10 BYTE), 
	"CODEVTVA" NUMBER(10,0), /*FK(AD_TGFECUS.CODEVENTO)*/
	"QTDEVTVA" NUMBER(10,0), 
	"CODEVTVLR" NUMBER(10,0), /*FK(AD_TGFECUS.CODEVENTO)*/
	"QTDEVTVLR" NUMBER(10,0), 
	"DHINS" DATE, 
	"USUINS" VARCHAR2(100 BYTE), 
	"DHUPD" DATE, 
	"USUUPD" VARCHAR2(100 BYTE)
   ) 
/

/*
NomeObjeto: MGSTCTEVTCUS
TipoObjeto: TABLE
NomeTabela: MGSTCTEVTCUS
Executar  : SE_NAO_EXISTIR
*/ 

CREATE TABLE "MGSTCTEVTCUS"
   (
    "NUEVTCUS" NUMBER(10,0), /*PK*/
	"NUMCONTRATO" NUMBER(10,0), /*FK(MGSTCTCONTRATO.NUMCONTRATO)*/
	"CODEVENTO" NUMBER(10,0), /*FK(AD_TGFECUS.CODEVENTO)*/
	"CODCUSTO" NUMBER(10,0), /*FK(AD_TGFPCUS.CODCUSTO)*/
	"CODTIPOFATURA" NUMBER(10,0), /*FK(MGSTCTTIPOFATURA.CODTIPOFATURA)*/
	"LCNUMDOCLANC" VARCHAR2(100 BYTE), 
	"LCHISTORICO" VARCHAR2(100 BYTE), 
	"LCSOMAQTDE" VARCHAR2(100 BYTE), 
	"LCCOMPLNUMDOC" VARCHAR2(100 BYTE), 
	"LCCOMPLHISTORICO" VARCHAR2(100 BYTE), 
	"LCDIA" VARCHAR2(100 BYTE), 
	"DHINS" DATE, 
	"USUINS" VARCHAR2(100 BYTE), 
	"DHUPD" DATE, 
	"USUUPD" VARCHAR2(100 BYTE)
   ) 
/

/*
NomeObjeto: MGSTCTEVTMENSAL
TipoObjeto: TABLE
NomeTabela: MGSTCTEVTMENSAL
Executar  : SE_NAO_EXISTIR
*/ 

CREATE TABLE "MGSTCTEVTMENSAL"
   (
    "NUEVTMENSAL" NUMBER(10,0), /*PK*/
	"NUMODALIDADE" NUMBER(10,0), /*FK(MGSTCTMODALCONTR.NUMODALIDADE)*/
	"NUMCONTRATO" NUMBER(10,0), /*FK(MGSTCTCONTRATO.NUMCONTRATO)*/
	"CODUNIDADEFATUR" NUMBER(10,0), /*FK(TGFSIT.CODSITE)*/
	"CODVAGA" VARCHAR2(10), 
	"CODSERVMATERIAL" NUMBER(10,0), 
	"CODTIPOPOSTO" NUMBER(10,0), 
	"CODCARGO" NUMBER(10,0), 
	"CODPRONTUARIO" NUMBER(10,0), 
	"NOME" VARCHAR2(100 BYTE), 
	"CODEVENTO" NUMBER(10,0), /*FK(AD_TGFECUS.CODEVENTO)*/
	"DTINIEVENTO" DATE, 
	"DTFIMEVENTO" DATE, 
	"DSCEVENTO" VARCHAR2(100 BYTE), 
	"INFEVENTO" VARCHAR2(100 BYTE), 
	"VLRUNIEVENTO" FLOAT(126), 
	"QTDEVENTO" NUMBER(10,0), 
	"VLRTOTEVENTO" FLOAT(126), 
	"COMPEVENTO" NUMBER(10,0), 
	"COMPLANC" NUMBER(10,0), 
	"COMPFATU" NUMBER(10,0), 
	"TIPLANCEVENTO" VARCHAR2(100 BYTE), 
	"CODSITLANC" NUMBER(10,0), 
	"CODINTEGRACAODC" NUMBER(10,0), /*FK(AD_CTINTEGRADC.IDINTEGRADC)*/
	"NUMSEQINTEGRACAO" NUMBER(10,0), 
	"CODCARGA" NUMBER(10,0), 
	"MTVCARGA" VARCHAR2(100 BYTE), 
	"PERCITF" FLOAT(126), 
	"PERCTXADM" FLOAT(126), 
	"VLRTXADM" FLOAT(126), 
	"DTLCCUSTO" DATE, 
	"CODCUSTO" NUMBER(10,0), /*FK(AD_TGFPCUS.CODCUSTO)*/
	"CODTIPOFATURA" NUMBER(10,0), /*FK(MGSTCTLOCALTIPOFAT.NUTIPOFATURA)*/
	"CODINTEGRACAOLC" NUMBER(10,0), /*FK(AD_CTINTEGRALC.IDINTEGRALC)*/
	"DTALTERLANC" DATE, 
	"USUALTERLANC" VARCHAR2(100 BYTE), 
	"CODUNIDADEFATURANT" VARCHAR2(100 BYTE), 
	"DTUNIDADEFATURANT" DATE, 
	"CODAPONTAMENTO" VARCHAR2(100 BYTE), 
	"TIPAPONTAMENTO" VARCHAR2(100 BYTE), 
	"CODORIGEM" VARCHAR2(100 BYTE), 
	"IDEVENTOREF" NUMBER(10,0), 
	"IDEVENTOREFGLOSA" NUMBER(10,0), 
	"VERVLR" VARCHAR2(100 BYTE), 
	"DHINS" DATE, 
	"USUINS" VARCHAR2(100 BYTE), 
	"TERMINS" VARCHAR2(100 BYTE), 
	"DHUPD" DATE, 
	"USUUPD" VARCHAR2(100 BYTE)
   ) 
/

/*
NomeObjeto: MGSTCTLCTCUSTO
TipoObjeto: TABLE
NomeTabela: MGSTCTLCTCUSTO
Executar  : SE_NAO_EXISTIR
*/ 

CREATE TABLE "MGSTCTLCTCUSTO"
   (
    "NULCTCUSTO" NUMBER(10,0), /*PK*/
	"NUMODALIDADE" NUMBER(10,0), /*FK(MGSTCTMODALCONTR.NUMODALIDADE)*/
	"NUMCONTRATO" NUMBER(10,0), /*FK(MGSTCTCONTRATO.NUMCONTRATO)*/
	"CODCUSTO" NUMBER(10,0), /*FK(AD_TGFPCUS.CODCUSTO)*/
	"CODTIPOFATURA" NUMBER(10,0), /*FK(MGSTCTTIPOFATURA.CODTIPOFATURA)*/
	"CODUNIDADEFATUR" NUMBER(10,0), /*FK(TGFSIT.CODSITE)*/
	"TIPGESTOR" VARCHAR2(100 BYTE), 
	"DTLANCCUSTO" DATE, 
	"ORIGEMLANC" VARCHAR2(100 BYTE), 
	"NUMDOCLANC" VARCHAR2(100 BYTE), 
	"HISTLANC" VARCHAR2(100 BYTE), 
	"VLRLANCCUSTO" FLOAT(126), 
	"NUMFATURA" NUMBER(10,0), 
	"IDRLTANEXO" NUMBER(10,0), 
	"QTDLANC" NUMBER(10,0), 
	"CODTIPOPOSTO" NUMBER(10,0), 
	"CODEVENTO" NUMBER(10,0), /*FK(AD_TGFECUS.CODEVENTO)*/
	"CODINTEGRACAOLC" NUMBER(10,0), /*FK(AD_CTINTEGRALC.IDINTEGRALC)*/
	"CODINTEGRACAOLCPAI" NUMBER(10,0), /*FK(AD_CTINTEGRALC.IDINTEGRALC)*/
	"DHINS" DATE, 
	"USUINS" VARCHAR2(100 BYTE)
   ) 
/

/*
NomeObjeto: MGSTCTRLTANEXO
TipoObjeto: TABLE
NomeTabela: MGSTCTRLTANEXO
Executar  : SE_NAO_EXISTIR
*/ 

CREATE TABLE "MGSTCTRLTANEXO"
   (
    "NURLTANEXO" NUMBER(10,0), /*PK*/
	"NUMODALIDADE" NUMBER(10,0), /*FK(MGSTCTMODALCONTR.NUMODALIDADE)*/
	"NUMCONTRATO" NUMBER(10,0), /*FK(MGSTCTCONTRATO.NUMCONTRATO)*/
	"CODCUSTO" NUMBER(10,0), /*FK(AD_TGFPCUS.CODCUSTO)*/
	"CODTIPOFATURA" NUMBER(10,0), /*FK(MGSTCTTIPOFATURA.CODTIPOFATURA)*/
	"CODUNIDADEFATUR" NUMBER(10,0), /*FK(TGFSIT.CODSITE)*/
	"TIPGESTOR" VARCHAR2(100 BYTE), 
	"DTRLTANEXO" DATE, 
	"APROVADO" VARCHAR2(10 BYTE), 
	"DHAPROVACAO" DATE, 
	"USUAPROVACAO" VARCHAR2(100 BYTE), 
	"DHINS" DATE, 
	"USUINS" VARCHAR2(100 BYTE)
   ) 
/

/*
NomeObjeto: MGSTCTFTRANEXO
TipoObjeto: TABLE
NomeTabela: MGSTCTFTRANEXO
Executar  : SE_NAO_EXISTIR
*/ 

CREATE TABLE "MGSTCTFTRANEXO"
   (
    "NUFTRANEXO" NUMBER(10,0), /*PK*/
	"NUFATURA" NUMBER(10,0), /*FK(MGSTCTFATURA.NUFATURA)*/
	"ASSINADO" VARCHAR2(10 BYTE), 
	"DHASSINADO" VARCHAR2(100 BYTE), 
	"DHINS" DATE, 
	"USUINS" VARCHAR2(100 BYTE)
   ) 
/

/*
NomeObjeto: MGSTCTINTEGRADC
TipoObjeto: TABLE
NomeTabela: MGSTCTINTEGRADC
Executar  : SE_NAO_EXISTIR
*/ 

CREATE TABLE "MGSTCTINTEGRADC"
   (
    "NUINTEGRADC" NUMBER(10,0), /*PK*/
	"NUMCONTRATO" NUMBER(10,0), /*FK(MGSTCTCONTRATO.NUMCONTRATO)*/
	"CODUNIDADEFATUR" NUMBER(10,0), /*FK(TGFSIT.CODSITE)*/
	"INTPERIODO" NUMBER(10,0), 
	"INTCOMPETENCIA" NUMBER(10,0), 
	"CODORIGEM" VARCHAR2(100 BYTE), 
	"TIPEXECUCAO" VARCHAR2(100 BYTE), 
	"COMPLEMENTO" VARCHAR2(100 BYTE), 
	"DHINS" DATE, 
	"USUINS" VARCHAR2(100 BYTE), 
	"DESFAZER" VARCHAR2(100 BYTE), 
	"DHDESFAZER" DATE, 
	"USUDESFAZER" VARCHAR2(100 BYTE)
   ) 
/

/*
NomeObjeto: MGSTCTINTEGRALC
TipoObjeto: TABLE
NomeTabela: MGSTCTINTEGRALC
Executar  : SE_NAO_EXISTIR
*/ 

CREATE TABLE "MGSTCTINTEGRALC"
   (
    "NUINTEGRALC" NUMBER(10,0), /*PK*/
	"NUMODALIDADE" NUMBER(10,0), /*FK(MGSTCTMODALCONTR.NUMODALIDADE)*/
	"NUMCONTRATO" NUMBER(10,0), /*FK(MGSTCTCONTRATO.NUMCONTRATO)*/
	"CODTIPOFATURA" NUMBER(10,0), /*FK(MGSTCTTIPOFATURA.CODTIPOFATURA)*/
	"CODUNIDADEFATUR" NUMBER(10,0), /*FK(TGFSIT.CODSITE)*/
	"DTLANCCUSTO" DATE, 
	"INTPERIODO" NUMBER(10,0), 
	"INTCOMPETENCIA" NUMBER(10,0), 
	"DHINS" DATE, 
	"USUINS" VARCHAR2(100 BYTE), 
	"DESFAZER" VARCHAR2(100 BYTE), 
	"DHDESFAZER" DATE, 
	"USUDESFAZER" VARCHAR2(100 BYTE)
   ) 
/

/*
NomeObjeto: MGSTCTFATURA
TipoObjeto: TABLE
NomeTabela: MGSTCTFATURA
Executar  : SE_NAO_EXISTIR
*/ 

CREATE TABLE "MGSTCTFATURA"
   (
    "NUFATURA" NUMBER(10,0), /*PK*/
	"NUCONTRCENT" NUMBER(10,0), 
	"NULOCALCONT" NUMBER(10,0), 
	"CODTIPOFATURA" NUMBER(10,0), /*FK(MGSTCTTIPOFATURA.CODTIPOFATURA)*/
	"NUMCONTRATO" NUMBER(10,0), /*FK(MGSTCTCONTRATO.NUMCONTRATO)*/
	"NUMODALIDADE" NUMBER(10,0), /*FK(MGSTCTMODALCONTR.NUMODALIDADE)*/
	"CODSITEPAI" NUMBER(10,0), 
	"SITUACAOFATU" NUMBER(10,0), 
	"DTREFERENCIA" DATE, 
	"DTGERACAO" DATE, 
	"DTEMISSAO" DATE, 
	"DTVENCIMENTO" DATE, 
	"DTCANCELAMENTO" DATE, 
	"VLRFATURA" FLOAT(126), 
	"VLRBRUTO" FLOAT(126)
   ) 
/

/*
NomeObjeto: MGSTCTITEMFATURA
TipoObjeto: TABLE
NomeTabela: MGSTCTITEMFATURA
Executar  : SE_NAO_EXISTIR
*/ 

CREATE TABLE "MGSTCTITEMFATURA"
   (
    "NUITEMFATUR" NUMBER(10,0), /*PK*/
	"NUFATURA" NUMBER(10,0), /*FK(MGSTCTFATURA.NUFATURA)*/
	"VLRITEMFATU" FLOAT(126)
   ) 
/

/*
NomeObjeto: MGSTCTTAXAFATURA
TipoObjeto: TABLE
NomeTabela: MGSTCTTAXAFATURA
Executar  : SE_NAO_EXISTIR
*/ 

CREATE TABLE "MGSTCTTAXAFATURA"
   (
    "NUTAXAFATUR" NUMBER(10,0), /*PK*/
	"NUFATURA" NUMBER(10,0), /*FK(MGSTCTFATURA.NUFATURA)*/
	"CODTIPOFATURA" NUMBER(10,0), /*FK(MGSTCTTIPOFATURA.CODTIPOFATURA)*/
	"NUCONTRTAXA" NUMBER(10,0), 
	"CODTAXA" NUMBER(10,0), 
	"VLRTAXA" FLOAT(126)
   ) 
/

/*
NomeObjeto: MGSTCTTRIBUTOFATURA
TipoObjeto: TABLE
NomeTabela: MGSTCTTRIBUTOFATURA
Executar  : SE_NAO_EXISTIR
*/ 

CREATE TABLE "MGSTCTTRIBUTOFATURA"
   (
    "NUTRIBUTOFATUR" NUMBER(10,0), /*PK*/
	"NUFATURA" NUMBER(10,0), /*FK(MGSTCTFATURA.NUFATURA)*/
	"CODTIPOFATURA" NUMBER(10,0), /*FK(MGSTCTTIPOFATURA.CODTIPOFATURA)*/
	"NUCONTRTRIB" NUMBER(10,0), 
	"CODPROD" NUMBER(10,0) /*FK(TGFPRO.CODPROD)*/
   ) 
/

/*
NomeObjeto: MGSTCTNFENOTAS
TipoObjeto: TABLE
NomeTabela: MGSTCTNFENOTAS
Executar  : SE_NAO_EXISTIR
*/ 

CREATE TABLE "MGSTCTNFENOTAS"
   (
    "NUNFENOTAS" NUMBER(10,0), /*PK*/
	"NUFATURA" NUMBER(10,0), /*FK(MGSTCTFATURA.NUFATURA)*/
	"NUMNFE" VARCHAR2(100 BYTE), 
	"CODVERIFICACAO" VARCHAR2(100 BYTE), 
	"DTEMISSAONFE" DATE, 
	"DTGERACAONFE" DATE
   ) 
/

/*
NomeObjeto: MGSTCTBOLETOFATURA
TipoObjeto: TABLE
NomeTabela: MGSTCTBOLETOFATURA
Executar  : SE_NAO_EXISTIR
*/ 

CREATE TABLE "MGSTCTBOLETOFATURA"
   (
    "NUBOLETOFATUR" NUMBER(10,0), /*PK*/
	"NUFATURA" NUMBER(10,0), /*FK(MGSTCTFATURA.NUFATURA)*/
	"CODTIPOFATURA" NUMBER(10,0), /*FK(MGSTCTTIPOFATURA.CODTIPOFATURA)*/
	"VLRBOLETOTOTAL" FLOAT(126)
   ) 
/

/*
NomeObjeto: MGSTCTGERABOLETO
TipoObjeto: TABLE
NomeTabela: MGSTCTGERABOLETO
Executar  : SE_NAO_EXISTIR
*/ 

CREATE TABLE "MGSTCTGERABOLETO"
   (
    "NUGERABOLETO" NUMBER(10,0), /*PK*/
	"NUBOLETOFATUR" NUMBER(10,0), /*FK(MGSTCTBOLETOFATURA.NUBOLETOFATUR)*/
	"NUFATURA" NUMBER(10,0), /*FK(MGSTCTFATURA.NUFATURA)*/
	"CODTIPOFATURA" NUMBER(10,0), /*FK(MGSTCTTIPOFATURA.CODTIPOFATURA)*/
	"NUOCORRENCIA" NUMBER(10,0), 
	"NOSSONUMERO" NUMBER(10,0), 
	"VLRBOLETO" FLOAT(126), 
	"DTEMISSAO" DATE, 
	"DTVENCIMENTO" DATE, 
	"DTGERACAO" DATE, 
	"DTBAIXABANCO" DATE, 
	"DTCANCELAMENTO" DATE, 
	"MSGCANCELA" VARCHAR2(100 BYTE), 
	"DTLIQUIDACAO" DATE
   ) 
/

/*
NomeObjeto: MGSTCTPOSTOCARGO
TipoObjeto: TABLE
NomeTabela: MGSTCTPOSTOCARGO
Executar  : SE_NAO_EXISTIR
*/ 

CREATE TABLE "MGSTCTPOSTOCARGO"
	(
	 "NUPOSTOCARGO" NUMBER(10,0), /*PK*/
	 "CODCARGO" NUMBER(10,0),
	 "CODTIPOPOSTO" NUMBER(10,0) /*FK(AD_TGFPSS.CODPOSTO)*/
	)
/

/*
NomeObjeto: MGSVCTCARGO
TipoObjeto: VIEW
NomeTabela: MGSVCTCARGO
Executar  : SEMPRE
*/ 

CREATE OR REPLACE VIEW MGSVCTCARGO
AS SELECT * FROM VIEW_CARGO_RH
/

/*
NomeObjeto: PK_MGSTCTCONTRATO
TipoObjeto: PRIMARY KEY
NomeTabela: MGSTCTCONTRATO
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTCONTRATO" ADD CONSTRAINT "PK_MGSTCTCONTRATO" PRIMARY KEY ("NUMCONTRATO") ENABLE 
/

/*
NomeObjeto: PK_MGSTCTMODALCONTR
TipoObjeto: PRIMARY KEY
NomeTabela: MGSTCTMODALCONTR
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTMODALCONTR" ADD CONSTRAINT "PK_MGSTCTMODALCONTR" PRIMARY KEY ("NUMODALIDADE") ENABLE 
/

/*
NomeObjeto: PK_MGSTCTCONTRATOPREV
TipoObjeto: PRIMARY KEY
NomeTabela: MGSTCTCONTRATOPREV
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTCONTRATOPREV" ADD CONSTRAINT "PK_MGSTCTCONTRATOPREV" PRIMARY KEY ("NUCONTRPREV") ENABLE 
/

/*
NomeObjeto: PK_MGSTCTLOCALCONT
TipoObjeto: PRIMARY KEY
NomeTabela: MGSTCTLOCALCONT
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTLOCALCONT" ADD CONSTRAINT "PK_MGSTCTLOCALCONT" PRIMARY KEY ("NULOCALCONT") ENABLE 
/

/*
NomeObjeto: PK_MGSTCTCONTRCENT
TipoObjeto: PRIMARY KEY
NomeTabela: MGSTCTCONTRCENT
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTCONTRCENT" ADD CONSTRAINT "PK_MGSTCTCONTRCENT" PRIMARY KEY ("NUCONTRCENT") ENABLE 
/

/*
NomeObjeto: PK_MGSTCTLOCALTIPOFAT
TipoObjeto: PRIMARY KEY
NomeTabela: MGSTCTLOCALTIPOFAT
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTLOCALTIPOFAT" ADD CONSTRAINT "PK_MGSTCTLOCALTIPOFAT" PRIMARY KEY ("NULOCALTIPOFAT") ENABLE 
/

/*
NomeObjeto: PK_MGSTCTTIPOFATURA
TipoObjeto: PRIMARY KEY
NomeTabela: MGSTCTTIPOFATURA
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTTIPOFATURA" ADD CONSTRAINT "PK_MGSTCTTIPOFATURA" PRIMARY KEY ("CODTIPOFATURA") ENABLE 
/

/*
NomeObjeto: PK_MGSTCTCONTRATOTRIB
TipoObjeto: PRIMARY KEY
NomeTabela: MGSTCTCONTRATOTRIB
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTCONTRATOTRIB" ADD CONSTRAINT "PK_MGSTCTCONTRATOTRIB" PRIMARY KEY ("NUCONTRATOTRIB") ENABLE 
/

/*
NomeObjeto: PK_MGSTCTCONTRATOTAXA
TipoObjeto: PRIMARY KEY
NomeTabela: MGSTCTCONTRATOTAXA
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTCONTRATOTAXA" ADD CONSTRAINT "PK_MGSTCTCONTRATOTAXA" PRIMARY KEY ("NUCONTRTAXA") ENABLE 
/

/*
NomeObjeto: PK_MGSTCTTIPOTAXA
TipoObjeto: PRIMARY KEY
NomeTabela: MGSTCTTIPOTAXA
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTTIPOTAXA" ADD CONSTRAINT "PK_MGSTCTTIPOTAXA" PRIMARY KEY ("CODTAXA") ENABLE 
/

/*
NomeObjeto: PK_MGSTCTUNIDADEPREV
TipoObjeto: PRIMARY KEY
NomeTabela: MGSTCTUNIDADEPREV
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTUNIDADEPREV" ADD CONSTRAINT "PK_MGSTCTUNIDADEPREV" PRIMARY KEY ("NUUNIDPREV") ENABLE 
/

/*
NomeObjeto: PK_MGSTCTCONTROLE
TipoObjeto: PRIMARY KEY
NomeTabela: MGSTCTCONTROLE
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTCONTROLE" ADD CONSTRAINT "PK_MGSTCTCONTROLE" PRIMARY KEY ("CODCONTROLE") ENABLE 
/

/*
NomeObjeto: PK_MGSTCTTIPOSITUACAO
TipoObjeto: PRIMARY KEY
NomeTabela: MGSTCTTIPOSITUACAO
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTTIPOSITUACAO" ADD CONSTRAINT "PK_MGSTCTTIPOSITUACAO" PRIMARY KEY ("CODTIPSITUACAO") ENABLE 
/

/*
NomeObjeto: PK_MGSTCTMETRICAS
TipoObjeto: PRIMARY KEY
NomeTabela: MGSTCTMETRICAS
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTMETRICAS" ADD CONSTRAINT "PK_MGSTCTMETRICAS" PRIMARY KEY ("NUMETRICAS") ENABLE 
/

/*
NomeObjeto: PK_MGSTCTUNIDPREVVAGA
TipoObjeto: PRIMARY KEY
NomeTabela: MGSTCTUNIDPREVVAGA
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTUNIDPREVVAGA" ADD CONSTRAINT "PK_MGSTCTUNIDPREVVAGA" PRIMARY KEY ("NUUNIDPREVVAGA") ENABLE 
/

/*
NomeObjeto: PK_MGSTCTVAGAS
TipoObjeto: PRIMARY KEY
NomeTabela: MGSTCTVAGAS
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTVAGAS" ADD CONSTRAINT "PK_MGSTCTVAGAS" PRIMARY KEY ("CODVAGA") ENABLE 
/

/*
NomeObjeto: PK_MGSTCTCONTRATOVAGA
TipoObjeto: PRIMARY KEY
NomeTabela: MGSTCTCONTRATOVAGA
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTCONTRATOVAGA" ADD CONSTRAINT "PK_MGSTCTCONTRATOVAGA" PRIMARY KEY ("NUCONTRVAGA") ENABLE 
/

/*
NomeObjeto: PK_MGSTCTCONTRVLRPS
TipoObjeto: PRIMARY KEY
NomeTabela: MGSTCTCONTRVLRPS
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTCONTRVLRPS" ADD CONSTRAINT "PK_MGSTCTCONTRVLRPS" PRIMARY KEY ("NUCONTREVENTO") ENABLE
/

/*
NomeObjeto: PK_MGSTCTCONTRVLRSERV
TipoObjeto: PRIMARY KEY
NomeTabela: MGSTCTCONTRVLRSERV
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTCONTRVLRSERV" ADD CONSTRAINT "PK_MGSTCTCONTRVLRSERV" PRIMARY KEY ("NUCONTRMATSRV") ENABLE
/

/*
NomeObjeto: PK_MGSTCTALOCACAOSERV
TipoObjeto: PRIMARY KEY
NomeTabela: MGSTCTALOCACAOSERV
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTALOCACAOSERV" ADD CONSTRAINT "PK_MGSTCTALOCACAOSERV" PRIMARY KEY ("NUALOCASERV") ENABLE
/

/*
NomeObjeto: PK_MGSTCTALOCACAOPS
TipoObjeto: PRIMARY KEY
NomeTabela: MGSTCTALOCACAOPS
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTALOCACAOPS" ADD CONSTRAINT "PK_MGSTCTALOCACAOPS" PRIMARY KEY ("NUALOCAPS") ENABLE
/

/*
NomeObjeto: PK_MGSTCTEVTAPT
TipoObjeto: PRIMARY KEY
NomeTabela: MGSTCTEVTAPT
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTEVTAPT" ADD CONSTRAINT "PK_MGSTCTEVTAPT" PRIMARY KEY ("NUEVTAPT") ENABLE
/

/*
NomeObjeto: PK_MGSTCTEVTCUS
TipoObjeto: PRIMARY KEY
NomeTabela: MGSTCTEVTCUS
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTEVTCUS" ADD CONSTRAINT "PK_MGSTCTEVTCUS" PRIMARY KEY ("NUEVTCUS") ENABLE
/

/*
NomeObjeto: PK_MGSTCTEVTMENSAL
TipoObjeto: PRIMARY KEY
NomeTabela: MGSTCTEVTMENSAL
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTEVTMENSAL" ADD CONSTRAINT "PK_MGSTCTEVTMENSAL" PRIMARY KEY ("NUEVTMENSAL") ENABLE
/

/*
NomeObjeto: PK_MGSTCTLCTCUSTO
TipoObjeto: PRIMARY KEY
NomeTabela: MGSTCTLCTCUSTO
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTLCTCUSTO" ADD CONSTRAINT "PK_MGSTCTLCTCUSTO" PRIMARY KEY ("NULCTCUSTO") ENABLE
/

/*
NomeObjeto: PK_MGSTCTRLTANEXO
TipoObjeto: PRIMARY KEY
NomeTabela: MGSTCTRLTANEXO
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTRLTANEXO" ADD CONSTRAINT "PK_MGSTCTRLTANEXO" PRIMARY KEY ("NURLTANEXO") ENABLE
/

/*
NomeObjeto: PK_MGSTCTFTRANEXO
TipoObjeto: PRIMARY KEY
NomeTabela: MGSTCTFTRANEXO
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTFTRANEXO" ADD CONSTRAINT "PK_MGSTCTFTRANEXO" PRIMARY KEY ("NUFTRANEXO") ENABLE
/

/*
NomeObjeto: PK_MGSTCTINTEGRADC
TipoObjeto: PRIMARY KEY
NomeTabela: MGSTCTINTEGRADC
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTINTEGRADC" ADD CONSTRAINT "PK_MGSTCTINTEGRADC" PRIMARY KEY ("NUINTEGRADC") ENABLE
/

/*
NomeObjeto: PK_MGSTCTINTEGRALC
TipoObjeto: PRIMARY KEY
NomeTabela: MGSTCTINTEGRALC
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTINTEGRALC" ADD CONSTRAINT "PK_MGSTCTINTEGRALC" PRIMARY KEY ("NUINTEGRALC") ENABLE
/

/*
NomeObjeto: PK_MGSTCTFATURA
TipoObjeto: PRIMARY KEY
NomeTabela: MGSTCTFATURA
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTFATURA" ADD CONSTRAINT "PK_MGSTCTFATURA" PRIMARY KEY ("NUFATURA") ENABLE
/

/*
NomeObjeto: PK_MGSTCTITEMFATURA
TipoObjeto: PRIMARY KEY
NomeTabela: MGSTCTITEMFATURA
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTITEMFATURA" ADD CONSTRAINT "PK_MGSTCTITEMFATURA" PRIMARY KEY ("NUITEMFATUR") ENABLE
/

/*
NomeObjeto: PK_MGSTCTTAXAFATURA
TipoObjeto: PRIMARY KEY
NomeTabela: MGSTCTTAXAFATURA
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTTAXAFATURA" ADD CONSTRAINT "PK_MGSTCTTAXAFATURA" PRIMARY KEY ("NUTAXAFATUR") ENABLE
/

/*
NomeObjeto: PK_MGSTCTTRIBUTOFATURA
TipoObjeto: PRIMARY KEY
NomeTabela: MGSTCTTRIBUTOFATURA
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTTRIBUTOFATURA" ADD CONSTRAINT "PK_MGSTCTTRIBUTOFATURA" PRIMARY KEY ("NUTRIBUTOFATUR") ENABLE
/

/*
NomeObjeto: PK_MGSTCTNFENOTAS
TipoObjeto: PRIMARY KEY
NomeTabela: MGSTCTNFENOTAS
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTNFENOTAS" ADD CONSTRAINT "PK_MGSTCTNFENOTAS" PRIMARY KEY ("NUNFENOTAS") ENABLE
/

/*
NomeObjeto: PK_MGSTCTBOLETOFATURA
TipoObjeto: PRIMARY KEY
NomeTabela: MGSTCTBOLETOFATURA
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTBOLETOFATURA" ADD CONSTRAINT "PK_MGSTCTBOLETOFATURA" PRIMARY KEY ("NUBOLETOFATUR") ENABLE
/

/*
NomeObjeto: PK_MGSTCTGERABOLETO
TipoObjeto: PRIMARY KEY
NomeTabela: MGSTCTGERABOLETO
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTGERABOLETO" ADD CONSTRAINT "PK_MGSTCTGERABOLETO" PRIMARY KEY ("NUGERABOLETO") ENABLE
/

/*
NomeObjeto: PK_MGSTCTPOSTOCARGO
TipoObjeto: PRIMARY KEY
NomeTabela: MGSTCTPOSTOCARGO
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTPOSTOCARGO" ADD CONSTRAINT "PK_MGSTCTPOSTOCARGO" PRIMARY KEY ("NUPOSTOCARGO") ENABLE
/

/*
NomeObjeto: FK_CONTRATO_TIPOSITUACAO
TipoObjeto: FOREIGN KEY
NomeTabela: MGSTCTCONTRATO
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTCONTRATO" ADD CONSTRAINT "FK_CONTRATO_TIPOSITUACAO" FOREIGN KEY ("CODTIPSITUACAO") 
	  REFERENCES "MGSTCTTIPOSITUACAO" ("CODTIPSITUACAO")
/

/*
NomeObjeto: FK_CONTRATO_TGFPAR
TipoObjeto: FOREIGN KEY
NomeTabela: MGSTCTCONTRATO
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTCONTRATO" ADD CONSTRAINT "FK_CONTRATO_TGFPAR" FOREIGN KEY ("CODPARC") 
	  REFERENCES "TGFPAR" ("CODPARC")
/

/*
NomeObjeto: FK_MODALCONTR_CONTRATO
TipoObjeto: FOREIGN KEY
NomeTabela: MGSTCTMODALCONTR
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTMODALCONTR" ADD CONSTRAINT "FK_MODALCONTR_CONTRATO" FOREIGN KEY ("NUMCONTRATO") 
	  REFERENCES "MGSTCTCONTRATO" ("NUMCONTRATO")
/

/*
NomeObjeto: FK_MODALCONTR_TCSTPN
TipoObjeto: FOREIGN KEY
NomeTabela: MGSTCTMODALCONTR
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTMODALCONTR" ADD CONSTRAINT "FK_MODALCONTR_TCSTPN" FOREIGN KEY ("CODTPN") 
	  REFERENCES "TCSTPN" ("CODTPN")
/

/*
NomeObjeto: FK_MODALCONTR_ADTGFTSE
TipoObjeto: FOREIGN KEY
NomeTabela: MGSTCTMODALCONTR
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTMODALCONTR" ADD CONSTRAINT "FK_MODALCONTR_ADTGFTSE" FOREIGN KEY ("NUTIPOSERVICO") 
	  REFERENCES "AD_TGFTSE" ("NUTIPOSERVICO")
/

/*
NomeObjeto: FK_CONTRATOPREV_MODALCONTR
TipoObjeto: FOREIGN KEY
NomeTabela: MGSTCTCONTRATOPREV
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTCONTRATOPREV" ADD CONSTRAINT "FK_CONTRATOPREV_MODALCONTR" FOREIGN KEY ("NUMODALIDADE") 
	  REFERENCES "MGSTCTMODALCONTR" ("NUMODALIDADE")
/

/*
NomeObjeto: FK_CONTRATOPREV_CONTRATO
TipoObjeto: FOREIGN KEY
NomeTabela: MGSTCTCONTRATOPREV
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTCONTRATOPREV" ADD CONSTRAINT "FK_CONTRATOPREV_CONTRATO" FOREIGN KEY ("NUMCONTRATO") 
	  REFERENCES "MGSTCTCONTRATO" ("NUMCONTRATO")
/

/*
NomeObjeto: FK_CONTRATOPREV_ADTGFPSS
TipoObjeto: FOREIGN KEY
NomeTabela: MGSTCTCONTRATOPREV
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTCONTRATOPREV" ADD CONSTRAINT "FK_CONTRATOPREV_ADTGFPSS" FOREIGN KEY ("CODTIPOPOSTO") 
	  REFERENCES "AD_TGFPSS" ("CODPOSTO")
/

/*
NomeObjeto: FK_CONTRATOPREV_ADTGFECUS
TipoObjeto: FOREIGN KEY
NomeTabela: MGSTCTCONTRATOPREV
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTCONTRATOPREV" ADD CONSTRAINT "FK_CONTRATOPREV_ADTGFECUS" FOREIGN KEY ("CODEVENTO") 
	  REFERENCES "AD_TGFECUS" ("CODEVENTO")
/

/*
NomeObjeto: FK_CONTRATOPREV_CTCONTROLE
TipoObjeto: FOREIGN KEY
NomeTabela: MGSTCTCONTRATOPREV
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTCONTRATOPREV" ADD CONSTRAINT "FK_CONTRATOPREV_CTCONTROLE" FOREIGN KEY ("CODCONTROLE") 
	  REFERENCES "MGSTCTCONTROLE" ("CODCONTROLE")
/

/

/*
NomeObjeto: FK_LOCALCONT_MODALCONTR
TipoObjeto: FOREIGN KEY
NomeTabela: MGSTCTLOCALCONT
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTLOCALCONT" ADD CONSTRAINT "FK_LOCALCONT_MODALCONTR" FOREIGN KEY ("NUMODALIDADE") 
	  REFERENCES "MGSTCTMODALCONTR" ("NUMODALIDADE")
/

/*
NomeObjeto: FK_LOCALCONT_CONTRATO
TipoObjeto: FOREIGN KEY
NomeTabela: MGSTCTLOCALCONT
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTLOCALCONT" ADD CONSTRAINT "FK_LOCALCONT_CONTRATO" FOREIGN KEY ("NUMCONTRATO") 
	  REFERENCES "MGSTCTCONTRATO" ("NUMCONTRATO")
/

/*
NomeObjeto: FK_LOCALCONT_TGFPAR
TipoObjeto: FOREIGN KEY
NomeTabela: MGSTCTLOCALCONT
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTLOCALCONT" ADD CONSTRAINT "FK_LOCALCONT_TGFPAR" FOREIGN KEY ("CODPARC") 
	  REFERENCES "TGFPAR" ("CODPARC")
/

/*
NomeObjeto: FK_LOCALCONT_TSICID
TipoObjeto: FOREIGN KEY
NomeTabela: MGSTCTLOCALCONT
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTLOCALCONT" ADD CONSTRAINT "FK_LOCALCONT_TSICID" FOREIGN KEY ("CODCID") 
	  REFERENCES "TSICID" ("CODCID")
/

/*
NomeObjeto: FK_LOCALCONT_TSIBAI
TipoObjeto: FOREIGN KEY
NomeTabela: MGSTCTLOCALCONT
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTLOCALCONT" ADD CONSTRAINT "FK_LOCALCONT_TSIBAI" FOREIGN KEY ("CODBAI") 
	  REFERENCES "TSIBAI" ("CODBAI")
/

/*
NomeObjeto: FK_LOCALCONT_TSIEND
TipoObjeto: FOREIGN KEY
NomeTabela: MGSTCTLOCALCONT
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTLOCALCONT" ADD CONSTRAINT "FK_LOCALCONT_TSIEND" FOREIGN KEY ("CODEND") 
	  REFERENCES "TSIEND" ("CODEND")
/

/*
NomeObjeto: FK_LOCALCONT_TSIUFS
TipoObjeto: FOREIGN KEY
NomeTabela: MGSTCTLOCALCONT
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTLOCALCONT" ADD CONSTRAINT "FK_LOCALCONT_TSIUFS" FOREIGN KEY ("CODUF") 
	  REFERENCES "TSIUFS" ("CODUF")
/

/*
NomeObjeto: FK_LOCALCONT_TSICIDNF
TipoObjeto: FOREIGN KEY
NomeTabela: MGSTCTLOCALCONT
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTLOCALCONT" ADD CONSTRAINT "FK_LOCALCONT_TSICIDNF" FOREIGN KEY ("CODCIDNF") 
	  REFERENCES "TSICID" ("CODCID")
/

/

/*
NomeObjeto: FK_CONTRCENT_LOCALCONT
TipoObjeto: FOREIGN KEY
NomeTabela: MGSTCTCONTRCENT
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTCONTRCENT" ADD CONSTRAINT "FK_CONTRCENT_LOCALCONT" FOREIGN KEY ("NULOCALCONT") 
	  REFERENCES "MGSTCTLOCALCONT" ("NULOCALCONT")
/

/*
NomeObjeto: FK_CONTRCENT_CONTRATO
TipoObjeto: FOREIGN KEY
NomeTabela: MGSTCTCONTRCENT
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTCONTRCENT" ADD CONSTRAINT "FK_CONTRCENT_CONTRATO" FOREIGN KEY ("NUMCONTRATO") 
	  REFERENCES "MGSTCTCONTRATO" ("NUMCONTRATO")
/

/*
NomeObjeto: FK_CONTRCENT_TGFSIT_PAI
TipoObjeto: FOREIGN KEY
NomeTabela: MGSTCTCONTRCENT
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTCONTRCENT" ADD CONSTRAINT "FK_CONTRCENT_TGFSIT_PAI" FOREIGN KEY ("CODSITEPAI") 
	  REFERENCES "TGFSIT" ("CODSITE")
/

/*
NomeObjeto: FK_CONTRCENT_TGFSIT
TipoObjeto: FOREIGN KEY
NomeTabela: MGSTCTCONTRCENT
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTCONTRCENT" ADD CONSTRAINT "FK_CONTRCENT_TGFSIT" FOREIGN KEY ("CODSITE") 
	  REFERENCES "TGFSIT" ("CODSITE")
/

/*
NomeObjeto: FK_LOCALTIPOFAT_TIPOFATURA
TipoObjeto: FOREIGN KEY
NomeTabela: MGSTCTLOCALTIPOFAT
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTLOCALTIPOFAT" ADD CONSTRAINT "FK_LOCALTIPOFAT_TIPOFATURA" FOREIGN KEY ("CODTIPOFATURA") 
	  REFERENCES "MGSTCTTIPOFATURA" ("CODTIPOFATURA")
/

/*
NomeObjeto: FK_LOCALTIPOFAT_LOCALCONT
TipoObjeto: FOREIGN KEY
NomeTabela: MGSTCTLOCALTIPOFAT
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTLOCALTIPOFAT" ADD CONSTRAINT "FK_LOCALTIPOFAT_LOCALCONT" FOREIGN KEY ("NULOCALCONT") 
	  REFERENCES "MGSTCTLOCALCONT" ("NULOCALCONT")
/

/*
NomeObjeto: FK_LOCALTIPOFAT_CONTRATO
TipoObjeto: FOREIGN KEY
NomeTabela: MGSTCTLOCALTIPOFAT
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTLOCALTIPOFAT" ADD CONSTRAINT "FK_LOCALTIPOFAT_CONTRATO" FOREIGN KEY ("NUMCONTRATO") 
	  REFERENCES "MGSTCTCONTRATO" ("NUMCONTRATO")
/

/*
NomeObjeto: FK_CONTRATOTRIB_LOCALTIPOFAT
TipoObjeto: FOREIGN KEY
NomeTabela: MGSTCTCONTRATOTRIB
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTCONTRATOTRIB" ADD CONSTRAINT "FK_CONTRATOTRIB_LOCALTIPOFAT" FOREIGN KEY ("NULOCALTIPOFAT") 
	  REFERENCES "MGSTCTLOCALTIPOFAT" ("NULOCALTIPOFAT")
/

/*
NomeObjeto: FK_CONTRATOTRIB_TGFPRO
TipoObjeto: FOREIGN KEY
NomeTabela: MGSTCTCONTRATOTRIB
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTCONTRATOTRIB" ADD CONSTRAINT "FK_CONTRATOTRIB_TGFPRO" FOREIGN KEY ("CODPROD") 
	  REFERENCES "TGFPRO" ("CODPROD")
/

/*
NomeObjeto: FK_CONTRATOTAXA_LOCALTIPOFAT
TipoObjeto: FOREIGN KEY
NomeTabela: MGSTCTCONTRATOTAXA
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTCONTRATOTAXA" ADD CONSTRAINT "FK_CONTRATOTAXA_LOCALTIPOFAT" FOREIGN KEY ("NULOCALTIPOFAT") 
	  REFERENCES "MGSTCTLOCALTIPOFAT" ("NULOCALTIPOFAT")
/

/*
NomeObjeto: FK_UNIDADEPREV_CONTRCENT
TipoObjeto: FOREIGN KEY
NomeTabela: MGSTCTUNIDADEPREV
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTUNIDADEPREV" ADD CONSTRAINT "FK_UNIDADEPREV_CONTRCENT" FOREIGN KEY ("NUCONTRCENT") 
	  REFERENCES "MGSTCTCONTRCENT" ("NUCONTRCENT")
/

/*
NomeObjeto: FK_UNIDADEPREV_ADTGFPSS
TipoObjeto: FOREIGN KEY
NomeTabela: MGSTCTUNIDADEPREV
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTUNIDADEPREV" ADD CONSTRAINT "FK_UNIDADEPREV_ADTGFPSS" FOREIGN KEY ("CODTIPOPOSTO") 
	  REFERENCES "AD_TGFPSS" ("CODPOSTO")
/

/*
NomeObjeto: FK_UNIDADEPREV_ADTGFECUS
TipoObjeto: FOREIGN KEY
NomeTabela: MGSTCTUNIDADEPREV
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTUNIDADEPREV" ADD CONSTRAINT "FK_UNIDADEPREV_ADTGFECUS" FOREIGN KEY ("CODEVENTO") 
	  REFERENCES "AD_TGFECUS" ("CODEVENTO")
/

/*
NomeObjeto: FK_UNIDADEPREV_CONTROLE
TipoObjeto: FOREIGN KEY
NomeTabela: MGSTCTUNIDADEPREV
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTUNIDADEPREV" ADD CONSTRAINT "FK_UNIDADEPREV_CONTROLE" FOREIGN KEY ("CODCONTROLE") 
	  REFERENCES "MGSTCTCONTROLE" ("CODCONTROLE")
/

/*
NomeObjeto: FK_METRICAS_CONTRATO
TipoObjeto: FOREIGN KEY
NomeTabela: MGSTCTMETRICAS
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTMETRICAS" ADD CONSTRAINT "FK_METRICAS_CONTRATO" FOREIGN KEY ("NUMCONTRATO") 
	  REFERENCES "MGSTCTCONTRATO" ("NUMCONTRATO")
/

/*
NomeObjeto: FK_UNIDPREVVAGA_CONTRCENT
TipoObjeto: FOREIGN KEY
NomeTabela: MGSTCTUNIDPREVVAGA
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTUNIDPREVVAGA" ADD CONSTRAINT "FK_UNIDPREVVAGA_CONTRCENT" FOREIGN KEY ("NUCONTRCENT") 
	  REFERENCES "MGSTCTCONTRCENT" ("NUCONTRCENT")
/

/*
NomeObjeto: FK_UNIDPREVVAGA_UNIDADEPREV
TipoObjeto: FOREIGN KEY
NomeTabela: MGSTCTUNIDPREVVAGA
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTUNIDPREVVAGA" ADD CONSTRAINT "FK_UNIDPREVVAGA_UNIDADEPREV" FOREIGN KEY ("NUUNIDPREV") 
	  REFERENCES "MGSTCTUNIDADEPREV" ("NUUNIDPREV")
/

/*
NomeObjeto: FK_CONTRATOVAGA_CONTRATOPREV
TipoObjeto: FOREIGN KEY
NomeTabela: MGSTCTCONTRATOVAGA
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTCONTRATOVAGA" ADD CONSTRAINT "FK_CONTRATOVAGA_CONTRATOPREV" FOREIGN KEY ("NUCONTRPREV") 
	  REFERENCES "MGSTCTCONTRATOPREV" ("NUCONTRPREV")
/

/*
NomeObjeto: FK_CONTRATOVAGA_VAGAS
TipoObjeto: FOREIGN KEY
NomeTabela: MGSTCTCONTRATOVAGA
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTCONTRATOVAGA" ADD CONSTRAINT "FK_CONTRATOVAGA_VAGAS" FOREIGN KEY ("CODVAGA") 
	  REFERENCES "MGSTCTVAGAS" ("CODVAGA")
/

/*
NomeObjeto: FK_CONTRVLRPS_CONTRATO
TipoObjeto: FOREIGN KEY
NomeTabela: MGSTCTCONTRVLRPS
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTCONTRVLRPS" ADD CONSTRAINT "FK_CONTRVLRPS_CONTRATO" FOREIGN KEY ("NUMCONTRATO") 
	  REFERENCES "MGSTCTCONTRATO" ("NUMCONTRATO")
/

/

/*
NomeObjeto: FK_CONTRVLRPS_MODALCONTR
TipoObjeto: FOREIGN KEY
NomeTabela: MGSTCTCONTRVLRPS
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTCONTRVLRPS" ADD CONSTRAINT "FK_CONTRVLRPS_MODALCONTR" FOREIGN KEY ("NUMODALIDADE") 
	  REFERENCES "MGSTCTMODALCONTR" ("NUMODALIDADE")
/

/*
NomeObjeto: FK_CONTRVLRPS_ADTGFPSS
TipoObjeto: FOREIGN KEY
NomeTabela: MGSTCTCONTRVLRPS
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTCONTRVLRPS" ADD CONSTRAINT "FK_CONTRVLRPS_ADTGFPSS" FOREIGN KEY ("CODTIPOPOSTO") 
	  REFERENCES "AD_TGFPSS" ("CODPOSTO")
/

/*
NomeObjeto: FK_CONTRVLRPS_ADTGFECUS
TipoObjeto: FOREIGN KEY
NomeTabela: MGSTCTCONTRVLRPS
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTCONTRVLRPS" ADD CONSTRAINT "FK_CONTRVLRPS_ADTGFECUS" FOREIGN KEY ("CODEVENTO") 
	  REFERENCES "AD_TGFECUS" ("CODEVENTO")
/

/*
NomeObjeto: FK_CONTRVLRSERV_CONTRATO
TipoObjeto: FOREIGN KEY
NomeTabela: MGSTCTCONTRVLRSERV
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTCONTRVLRSERV" ADD CONSTRAINT "FK_CONTRVLRSERV_CONTRATO" FOREIGN KEY ("NUMCONTRATO") 
	  REFERENCES "MGSTCTCONTRATO" ("NUMCONTRATO")
/

/*
NomeObjeto: FK_CONTRVLRSERV_MODALCONTR
TipoObjeto: FOREIGN KEY
NomeTabela: MGSTCTCONTRVLRSERV
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTCONTRVLRSERV" ADD CONSTRAINT "FK_CONTRVLRSERV_MODALCONTR" FOREIGN KEY ("NUMODALIDADE") 
	  REFERENCES "MGSTCTMODALCONTR" ("NUMODALIDADE")
/

/*
NomeObjeto: FK_CONTRVLRSERV_CODPROD
TipoObjeto: FOREIGN KEY
NomeTabela: MGSTCTCONTRVLRSERV
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTCONTRVLRSERV" ADD CONSTRAINT "FK_CONTRVLRSERV_CODPROD" FOREIGN KEY ("CODSERVMATERIAL") 
	  REFERENCES "TGFPRO" ("CODPROD")
/

/*
NomeObjeto: FK_CONTRVLRSERV_ADTGFECUS
TipoObjeto: FOREIGN KEY
NomeTabela: MGSTCTCONTRVLRSERV
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTCONTRVLRSERV" ADD CONSTRAINT "FK_CONTRVLRSERV_ADTGFECUS" FOREIGN KEY ("CODEVENTO") 
	  REFERENCES "AD_TGFECUS" ("CODEVENTO")
/

/*
NomeObjeto: FK_ALOCACAOSERV_NUUNIDPREV
TipoObjeto: FOREIGN KEY
NomeTabela: MGSTCTALOCACAOSERV
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTALOCACAOSERV" ADD CONSTRAINT "FK_ALOCACAOSERV_NUUNIDPREV" FOREIGN KEY ("NUUNIDPREV") 
	  REFERENCES "MGSTCTUNIDADEPREV" ("NUUNIDPREV")
/

/*
NomeObjeto: FK_ALOCACAOPS_UNIDADEPREV
TipoObjeto: FOREIGN KEY
NomeTabela: MGSTCTALOCACAOPS
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTALOCACAOPS" ADD CONSTRAINT "FK_ALOCACAOPS_UNIDADEPREV" FOREIGN KEY ("NUUNIDPREV") 
	  REFERENCES "MGSTCTUNIDADEPREV" ("NUUNIDPREV")
/

/*
NomeObjeto: FK_ALOCACAOPS_UNIDPREVVAGA
TipoObjeto: FOREIGN KEY
NomeTabela: MGSTCTALOCACAOPS
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTALOCACAOPS" ADD CONSTRAINT "FK_ALOCACAOPS_UNIDPREVVAGA" FOREIGN KEY ("NUUNIDPREVVAGA") 
	  REFERENCES "MGSTCTUNIDPREVVAGA" ("NUUNIDPREVVAGA")
/

/*
NomeObjeto: FK_ALOCACAOPS_ADTGFPSS
TipoObjeto: FOREIGN KEY
NomeTabela: MGSTCTALOCACAOPS
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTALOCACAOPS" ADD CONSTRAINT "FK_ALOCACAOPS_ADTGFPSS" FOREIGN KEY ("CODTIPOPOSTO") 
	  REFERENCES "AD_TGFPSS" ("CODPOSTO")
/

/*
NomeObjeto: FK_ALOCACAOPS_ADTGFECUS
TipoObjeto: FOREIGN KEY
NomeTabela: MGSTCTALOCACAOPS
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTALOCACAOPS" ADD CONSTRAINT "FK_ALOCACAOPS_ADTGFECUS" FOREIGN KEY ("CODEVENTO") 
	  REFERENCES "AD_TGFECUS" ("CODEVENTO")
/

/*
NomeObjeto: FK_EVTAPT_CONTRATO
TipoObjeto: FOREIGN KEY
NomeTabela: MGSTCTEVTAPT
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTEVTAPT" ADD CONSTRAINT "FK_EVTAPT_CONTRATO" FOREIGN KEY ("NUMCONTRATO") 
	  REFERENCES "MGSTCTCONTRATO" ("NUMCONTRATO")
/

/*
NomeObjeto: FK_EVTAPT_ADTGFECUS
TipoObjeto: FOREIGN KEY
NomeTabela: MGSTCTEVTAPT
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTEVTAPT" ADD CONSTRAINT "FK_EVTAPT_ADTGFECUS" FOREIGN KEY ("CODEVENTO") 
	  REFERENCES "AD_TGFECUS" ("CODEVENTO")
/

/*
NomeObjeto: FK_EVTAPT_ADTGFECUSVA
TipoObjeto: FOREIGN KEY
NomeTabela: MGSTCTEVTAPT
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTEVTAPT" ADD CONSTRAINT "FK_EVTAPT_ADTGFECUSVA" FOREIGN KEY ("CODEVTVA") 
	  REFERENCES "AD_TGFECUS" ("CODEVENTO")
/

/*
NomeObjeto: FK_EVTAPT_ADTGFECUSVLR
TipoObjeto: FOREIGN KEY
NomeTabela: MGSTCTEVTAPT
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTEVTAPT" ADD CONSTRAINT "FK_EVTAPT_ADTGFECUSVLR" FOREIGN KEY ("CODEVTVLR") 
	  REFERENCES "AD_TGFECUS" ("CODEVENTO")
/

/*
NomeObjeto: FK_EVTCUS_CONTRATO
TipoObjeto: FOREIGN KEY
NomeTabela: MGSTCTEVTCUS
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTEVTCUS" ADD CONSTRAINT "FK_EVTCUS_CONTRATO" FOREIGN KEY ("NUMCONTRATO") 
	  REFERENCES "MGSTCTCONTRATO" ("NUMCONTRATO")
/

/*
NomeObjeto: FK_EVTCUS_ADTGFECUS
TipoObjeto: FOREIGN KEY
NomeTabela: MGSTCTEVTCUS
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTEVTCUS" ADD CONSTRAINT "FK_EVTCUS_ADTGFECUS" FOREIGN KEY ("CODEVENTO") 
	  REFERENCES "AD_TGFECUS" ("CODEVENTO")
/

/*
NomeObjeto: FK_EVTCUS_ADTGFPCUS
TipoObjeto: FOREIGN KEY
NomeTabela: MGSTCTEVTCUS
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTEVTCUS" ADD CONSTRAINT "FK_EVTCUS_ADTGFPCUS" FOREIGN KEY ("CODCUSTO") 
	  REFERENCES "AD_TGFPCUS" ("CODCUSTO")
/

/*
NomeObjeto: FK_EVTCUS_TIPOFATURA
TipoObjeto: FOREIGN KEY
NomeTabela: MGSTCTEVTCUS
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTEVTCUS" ADD CONSTRAINT "FK_EVTCUS_TIPOFATURA" FOREIGN KEY ("CODTIPOFATURA") 
	  REFERENCES "MGSTCTTIPOFATURA" ("CODTIPOFATURA")
/

/*
NomeObjeto: FK_EVTMENSAL_MODALCONTR
TipoObjeto: FOREIGN KEY
NomeTabela: MGSTCTEVTMENSAL
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTEVTMENSAL" ADD CONSTRAINT "FK_EVTMENSAL_MODALCONTR" FOREIGN KEY ("NUMODALIDADE") 
	  REFERENCES "MGSTCTMODALCONTR" ("NUMODALIDADE")
/

/*
NomeObjeto: FK_EVTMENSAL_CONTRATO
TipoObjeto: FOREIGN KEY
NomeTabela: MGSTCTEVTMENSAL
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTEVTMENSAL" ADD CONSTRAINT "FK_EVTMENSAL_CONTRATO" FOREIGN KEY ("NUMCONTRATO") 
	  REFERENCES "MGSTCTCONTRATO" ("NUMCONTRATO")
/

/*
NomeObjeto: FK_EVTMENSAL_TGFSIT
TipoObjeto: FOREIGN KEY
NomeTabela: MGSTCTEVTMENSAL
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTEVTMENSAL" ADD CONSTRAINT "FK_EVTMENSAL_TGFSIT" FOREIGN KEY ("CODUNIDADEFATUR") 
	  REFERENCES "TGFSIT" ("CODSITE")
/

/*
NomeObjeto: FK_EVTMENSAL_ADTGFECUS
TipoObjeto: FOREIGN KEY
NomeTabela: MGSTCTEVTMENSAL
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTEVTMENSAL" ADD CONSTRAINT "FK_EVTMENSAL_ADTGFECUS" FOREIGN KEY ("CODEVENTO") 
	  REFERENCES "AD_TGFECUS" ("CODEVENTO")
/

/*
NomeObjeto: FK_EVTMENSAL_ADCTINTEGRADC
TipoObjeto: FOREIGN KEY
NomeTabela: MGSTCTEVTMENSAL
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTEVTMENSAL" ADD CONSTRAINT "FK_EVTMENSAL_ADCTINTEGRADC" FOREIGN KEY ("CODINTEGRACAODC") 
	  REFERENCES "AD_CTINTEGRADC" ("IDINTEGRADC")
/

/*
NomeObjeto: FK_EVTMENSAL_ADTGFECUS
TipoObjeto: FOREIGN KEY
NomeTabela: MGSTCTEVTMENSAL
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTEVTMENSAL" ADD CONSTRAINT "FK_EVTMENSAL_ADTGFECUS" FOREIGN KEY ("CODCUSTO") 
	  REFERENCES "AD_TGFPCUS" ("CODCUSTO")
/

/*
NomeObjeto: FK_EVTMENSAL_LOCALTIPOFAT
TipoObjeto: FOREIGN KEY
NomeTabela: MGSTCTEVTMENSAL
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTEVTMENSAL" ADD CONSTRAINT "FK_EVTMENSAL_LOCALTIPOFAT" FOREIGN KEY ("CODTIPOFATURA") 
	  REFERENCES "MGSTCTLOCALTIPOFAT" ("CODTIPOFATURA")
/

/*
NomeObjeto: FK_EVTMENSAL_ADCTINTEGRALC
TipoObjeto: FOREIGN KEY
NomeTabela: MGSTCTEVTMENSAL
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTEVTMENSAL" ADD CONSTRAINT "FK_EVTMENSAL_ADCTINTEGRALC" FOREIGN KEY ("CODINTEGRACAOLC") 
	  REFERENCES "AD_CTINTEGRALC" ("IDINTEGRALC")
/

/*
NomeObjeto: FK_LCTCUSTO_MODALCONTR
TipoObjeto: FOREIGN KEY
NomeTabela: MGSTCTLCTCUSTO
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTLCTCUSTO" ADD CONSTRAINT "FK_LCTCUSTO_MODALCONTR" FOREIGN KEY ("NUMODALIDADE") 
	  REFERENCES "MGSTCTMODALCONTR" ("NUMODALIDADE")
/

/*
NomeObjeto: FK_LCTCUSTO_CONTRATO
TipoObjeto: FOREIGN KEY
NomeTabela: MGSTCTLCTCUSTO
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTLCTCUSTO" ADD CONSTRAINT "FK_LCTCUSTO_CONTRATO" FOREIGN KEY ("NUMCONTRATO") 
	  REFERENCES "MGSTCTCONTRATO" ("NUMCONTRATO")
/

/*
NomeObjeto: FK_LCTCUSTO_ADTGFPCUS
TipoObjeto: FOREIGN KEY
NomeTabela: MGSTCTLCTCUSTO
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTLCTCUSTO" ADD CONSTRAINT "FK_LCTCUSTO_ADTGFPCUS" FOREIGN KEY ("CODCUSTO") 
	  REFERENCES "AD_TGFPCUS" ("CODCUSTO")
/

/*
NomeObjeto: FK_LCTCUSTO_TIPOFATURA
TipoObjeto: FOREIGN KEY
NomeTabela: MGSTCTLCTCUSTO
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTLCTCUSTO" ADD CONSTRAINT "FK_LCTCUSTO_TIPOFATURA" FOREIGN KEY ("CODTIPOFATURA") 
	  REFERENCES "MGSTCTTIPOFATURA" ("CODTIPOFATURA")
/

/*
NomeObjeto: FK_LCTCUSTO_TGFSIT
TipoObjeto: FOREIGN KEY
NomeTabela: MGSTCTLCTCUSTO
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTLCTCUSTO" ADD CONSTRAINT "FK_LCTCUSTO_TGFSIT" FOREIGN KEY ("CODUNIDADEFATUR") 
	  REFERENCES "TGFSIT" ("CODSITE")
/

/*
NomeObjeto: FK_LCTCUSTO_ADTGFECUS
TipoObjeto: FOREIGN KEY
NomeTabela: MGSTCTLCTCUSTO
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTLCTCUSTO" ADD CONSTRAINT "FK_LCTCUSTO_ADTGFECUS" FOREIGN KEY ("CODEVENTO") 
	  REFERENCES "AD_TGFECUS" ("CODEVENTO")
/

/*
NomeObjeto: FK_LCTCUSTO_ADCTINTEGRALC
TipoObjeto: FOREIGN KEY
NomeTabela: MGSTCTLCTCUSTO
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTLCTCUSTO" ADD CONSTRAINT "FK_LCTCUSTO_ADCTINTEGRALC" FOREIGN KEY ("CODINTEGRACAOLC") 
	  REFERENCES "AD_CTINTEGRALC" ("IDINTEGRALC")
/

/*
NomeObjeto: FK_LCTCUSTO_ADCTINTEGRALCPAI
TipoObjeto: FOREIGN KEY
NomeTabela: MGSTCTLCTCUSTO
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTLCTCUSTO" ADD CONSTRAINT "FK_LCTCUSTO_ADCTINTEGRALC" FOREIGN KEY ("CODINTEGRACAOLCPAI") 
	  REFERENCES "AD_CTINTEGRALC" ("IDINTEGRALC")
/

/*
NomeObjeto: FK_RLTANEXO_MODALCONTR
TipoObjeto: FOREIGN KEY
NomeTabela: MGSTCTRLTANEXO
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTRLTANEXO" ADD CONSTRAINT "FK_RLTANEXO_MODALCONTR" FOREIGN KEY ("NUMODALIDADE") 
	  REFERENCES "MGSTCTMODALCONTR" ("NUMODALIDADE")
/

/*
NomeObjeto: FK_RLTANEXO_CONTRATO
TipoObjeto: FOREIGN KEY
NomeTabela: MGSTCTRLTANEXO
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTRLTANEXO" ADD CONSTRAINT "FK_RLTANEXO_CONTRATO" FOREIGN KEY ("NUMCONTRATO") 
	  REFERENCES "MGSTCTCONTRATO" ("NUMCONTRATO")
/

/*
NomeObjeto: FK_RLTANEXO_ADTGFPCUS
TipoObjeto: FOREIGN KEY
NomeTabela: MGSTCTRLTANEXO
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTRLTANEXO" ADD CONSTRAINT "FK_RLTANEXO_ADTGFPCUS" FOREIGN KEY ("CODCUSTO") 
	  REFERENCES "AD_TGFPCUS" ("CODCUSTO")
/

/*
NomeObjeto: FK_RLTANEXO_TIPOFATURA
TipoObjeto: FOREIGN KEY
NomeTabela: MGSTCTRLTANEXO
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTRLTANEXO" ADD CONSTRAINT "FK_RLTANEXO_TIPOFATURA" FOREIGN KEY ("CODTIPOFATURA") 
	  REFERENCES "MGSTCTTIPOFATURA" ("CODTIPOFATURA")
/

/*
NomeObjeto: FK_RLTANEXO_TGFSIT
TipoObjeto: FOREIGN KEY
NomeTabela: MGSTCTRLTANEXO
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTRLTANEXO" ADD CONSTRAINT "FK_RLTANEXO_TGFSIT" FOREIGN KEY ("CODUNIDADEFATUR") 
	  REFERENCES "TGFSIT" ("CODSITE")
/

/*
NomeObjeto: FK_FTRANEXO_FATURA
TipoObjeto: FOREIGN KEY
NomeTabela: MGSTCTFTRANEXO
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTFTRANEXO" ADD CONSTRAINT "FK_FTRANEXO_FATURA" FOREIGN KEY ("NUFATURA") 
	  REFERENCES "MGSTCTFATURA" ("NUFATURA")
/

/*
NomeObjeto: FK_INTEGRADC_CONTRATO
TipoObjeto: FOREIGN KEY
NomeTabela: MGSTCTINTEGRADC
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTINTEGRADC" ADD CONSTRAINT "FK_INTEGRADC_CONTRATO" FOREIGN KEY ("NUMCONTRATO") 
	  REFERENCES "MGSTCTCONTRATO" ("NUMCONTRATO")
/

/*
NomeObjeto: FK_INTEGRADC_TGFSIT
TipoObjeto: FOREIGN KEY
NomeTabela: MGSTCTINTEGRADC
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTINTEGRADC" ADD CONSTRAINT "FK_INTEGRADC_TGFSIT" FOREIGN KEY ("CODUNIDADEFATUR") 
	  REFERENCES "TGFSIT" ("CODSITE")
/

/*
NomeObjeto: FK_INTEGRALC_MODALCONTR
TipoObjeto: FOREIGN KEY
NomeTabela: MGSTCTINTEGRALC
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTINTEGRALC" ADD CONSTRAINT "FK_INTEGRALC_MODALCONTR" FOREIGN KEY ("NUMODALIDADE") 
	  REFERENCES "MGSTCTMODALCONTR" ("NUMODALIDADE")
/

/*
NomeObjeto: FK_INTEGRALC_CONTRATO
TipoObjeto: FOREIGN KEY
NomeTabela: MGSTCTINTEGRALC
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTINTEGRALC" ADD CONSTRAINT "FK_INTEGRALC_CONTRATO" FOREIGN KEY ("NUMCONTRATO") 
	  REFERENCES "MGSTCTCONTRATO" ("NUMCONTRATO")
/

/*
NomeObjeto: FK_INTEGRALC_TIPOFATURA
TipoObjeto: FOREIGN KEY
NomeTabela: MGSTCTINTEGRALC
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTINTEGRALC" ADD CONSTRAINT "FK_INTEGRALC_TIPOFATURA" FOREIGN KEY ("CODTIPOFATURA") 
	  REFERENCES "MGSTCTTIPOFATURA" ("CODTIPOFATURA")
/

/*
NomeObjeto: FK_INTEGRALC_TGFSIT
TipoObjeto: FOREIGN KEY
NomeTabela: MGSTCTINTEGRALC
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTINTEGRALC" ADD CONSTRAINT "FK_INTEGRALC_TGFSIT" FOREIGN KEY ("CODUNIDADEFATUR") 
	  REFERENCES "TGFSIT" ("CODSITE")
/

/*
NomeObjeto: FK_FATURA_TIPOFATURA
TipoObjeto: FOREIGN KEY
NomeTabela: MGSTCTFATURA
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTFATURA" ADD CONSTRAINT "FK_FATURA_TIPOFATURA" FOREIGN KEY ("CODTIPOFATURA") 
	  REFERENCES "MGSTCTTIPOFATURA" ("CODTIPOFATURA")
/

/*
NomeObjeto: FK_FATURA_CONTRATO
TipoObjeto: FOREIGN KEY
NomeTabela: MGSTCTFATURA
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTFATURA" ADD CONSTRAINT "FK_FATURA_CONTRATO" FOREIGN KEY ("NUMCONTRATO") 
	  REFERENCES "MGSTCTCONTRATO" ("NUMCONTRATO")
/

/*
NomeObjeto: FK_FATURA_MODALCONTR
TipoObjeto: FOREIGN KEY
NomeTabela: MGSTCTFATURA
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTFATURA" ADD CONSTRAINT "FK_FATURA_MODALCONTR" FOREIGN KEY ("NUMODALIDADE") 
	  REFERENCES "MGSTCTMODALCONTR" ("NUMODALIDADE")
/

/*
NomeObjeto: FK_ITEMFATURA_FATURA
TipoObjeto: FOREIGN KEY
NomeTabela: MGSTCTITEMFATURA
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTITEMFATURA" ADD CONSTRAINT "FK_ITEMFATURA_FATURA" FOREIGN KEY ("NUFATURA") 
	  REFERENCES "MGSTCTFATURA" ("NUFATURA")
/

/*
NomeObjeto: FK_TAXAFATURA_FATURA
TipoObjeto: FOREIGN KEY
NomeTabela: MGSTCTTAXAFATURA
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTTAXAFATURA" ADD CONSTRAINT "FK_TAXAFATURA_FATURA" FOREIGN KEY ("NUFATURA") 
	  REFERENCES "MGSTCTFATURA" ("NUFATURA")
/

/*
NomeObjeto: FK_TAXAFATURA_TIPOFATURA
TipoObjeto: FOREIGN KEY
NomeTabela: MGSTCTTAXAFATURA
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTTAXAFATURA" ADD CONSTRAINT "FK_TAXAFATURA_TIPOFATURA" FOREIGN KEY ("CODTIPOFATURA") 
	  REFERENCES "MGSTCTTIPOFATURA" ("CODTIPOFATURA")
/

/*
NomeObjeto: FK_TRIBUTOFATURA_FATURA
TipoObjeto: FOREIGN KEY
NomeTabela: MGSTCTTRIBUTOFATURA
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTTRIBUTOFATURA" ADD CONSTRAINT "FK_TRIBUTOFATURA_FATURA" FOREIGN KEY ("NUFATURA") 
	  REFERENCES "MGSTCTFATURA" ("NUFATURA")
/

/*
NomeObjeto: FK_TRIBUTOFATURA_TIPOFATURA
TipoObjeto: FOREIGN KEY
NomeTabela: MGSTCTTRIBUTOFATURA
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTTRIBUTOFATURA" ADD CONSTRAINT "FK_TRIBUTOFATURA_TIPOFATURA" FOREIGN KEY ("CODTIPOFATURA") 
	  REFERENCES "MGSTCTTIPOFATURA" ("CODTIPOFATURA")
/

/*
NomeObjeto: FK_TRIBUTOFATURA_TGFPRO
TipoObjeto: FOREIGN KEY
NomeTabela: MGSTCTTRIBUTOFATURA
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTTRIBUTOFATURA" ADD CONSTRAINT "FK_TRIBUTOFATURA_TGFPRO" FOREIGN KEY ("CODPROD") 
	  REFERENCES "TGFPRO" ("CODPROD")
/

/*
NomeObjeto: FK_NFENOTAS_FATURA
TipoObjeto: FOREIGN KEY
NomeTabela: MGSTCTNFENOTAS
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTNFENOTAS" ADD CONSTRAINT "FK_NFENOTAS_FATURA" FOREIGN KEY ("NUFATURA") 
	  REFERENCES "MGSTCTFATURA" ("NUFATURA")
/

/*
NomeObjeto: FK_BOLETOFATURA_FATURA
TipoObjeto: FOREIGN KEY
NomeTabela: MGSTCTBOLETOFATURA
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTBOLETOFATURA" ADD CONSTRAINT "FK_BOLETOFATURA_FATURA" FOREIGN KEY ("NUFATURA") 
	  REFERENCES "MGSTCTFATURA" ("NUFATURA")
/

/*
NomeObjeto: FK_BOLETOFATURA_TIPOFATURA
TipoObjeto: FOREIGN KEY
NomeTabela: MGSTCTBOLETOFATURA
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTBOLETOFATURA" ADD CONSTRAINT "FK_BOLETOFATURA_TIPOFATURA" FOREIGN KEY ("CODTIPOFATURA") 
	  REFERENCES "MGSTCTTIPOFATURA" ("CODTIPOFATURA")
/

/*
NomeObjeto: FK_GERABOLETO_BOLETOFATURA
TipoObjeto: FOREIGN KEY
NomeTabela: MGSTCTGERABOLETO
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTGERABOLETO" ADD CONSTRAINT "FK_GERABOLETO_BOLETOFATURA" FOREIGN KEY ("NUBOLETOFATUR") 
	  REFERENCES "MGSTCTBOLETOFATURA" ("NUBOLETOFATUR")
/

/*
NomeObjeto: FK_GERABOLETO_FATURA
TipoObjeto: FOREIGN KEY
NomeTabela: MGSTCTGERABOLETO
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTGERABOLETO" ADD CONSTRAINT "FK_GERABOLETO_FATURA" FOREIGN KEY ("NUFATURA") 
	  REFERENCES "MGSTCTFATURA" ("NUFATURA")
/

/*
NomeObjeto: FK_GERABOLETO_TIPOFATURA
TipoObjeto: FOREIGN KEY
NomeTabela: MGSTCTGERABOLETO
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE "MGSTCTGERABOLETO" ADD CONSTRAINT "FK_GERABOLETO_TIPOFATURA" FOREIGN KEY ("CODTIPOFATURA") 
	  REFERENCES "MGSTCTTIPOFATURA" ("CODTIPOFATURA")
/

